include:
  - data.yaml
  - network.yaml
  - starrocks-separate-storage.yaml

services:
  jobmanager:
    build:
      context: .
    image: mysql-flink-starrocks:v1
    container_name: flink-jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
      - TZ=Asia/Jakarta 
    volumes:
      - data_smt:/opt/flink/smt
    networks:
      - lakwar-network

  taskmanager:
    image: mysql-flink-starrocks:v1
    container_name: flink-taskmanager
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
      - TZ=Asia/Jakarta
    volumes:
      - data_smt:/opt/flink/smt
    networks:
      - lakwar-network
    
  sql-client:
    image: mysql-flink-starrocks:v1
    container_name: flink-client
    command: bin/sql-client.sh
    depends_on:
      - jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        rest.address: jobmanager   
      - TZ=Asia/Jakarta
    volumes:
      - data_smt:/opt/flink/smt